using System;
using IPA.Config.Data;

namespace IPA.Config.Stores
{
	/// <summary>
	/// The base interface for a value converter for use by objects generated by
	/// <see cref="M:IPA.Config.Stores.GeneratedStore.Generated``1(IPA.Config.Config,System.Boolean)" />.
	/// </summary>
	/// <remarks>
	/// <para>
	/// The object returned from <see cref="M:IPA.Config.Stores.IValueConverter.FromValue(IPA.Config.Data.Value,System.Object)" />, if fed into <see cref="M:IPA.Config.Stores.IValueConverter.ToValue(System.Object,System.Object)" />,
	/// should return equivalent <see cref="T:IPA.Config.Data.Value" /> structures. Similarly, if the result of <see cref="M:IPA.Config.Stores.IValueConverter.ToValue(System.Object,System.Object)" />
	/// is fed into <see cref="M:IPA.Config.Stores.IValueConverter.FromValue(IPA.Config.Data.Value,System.Object)" />, the resulting object should be equivalent to the one passed to 
	/// <see cref="M:IPA.Config.Stores.IValueConverter.ToValue(System.Object,System.Object)" />.
	/// </para>
	/// <para>
	/// The <c>parent</c> parameter to <see cref="M:IPA.Config.Stores.IValueConverter.ToValue(System.Object,System.Object)" /> and <see cref="M:IPA.Config.Stores.IValueConverter.FromValue(IPA.Config.Data.Value,System.Object)" /> should
	/// be (ideally) the the top of the serialization tree, or some other generated object in that tree, rather than some arbitrary
	/// object in the middle that is not managed by the generatd config system.
	/// </para>
	/// <para>
	/// Converters do <i>not</i> need to perform null checks, as the serializer and deserializer will do that automatically.
	/// </para>
	/// </remarks>
	// Token: 0x02000066 RID: 102
	public interface IValueConverter
	{
		/// <summary>
		/// Converts the given object to a <see cref="T:IPA.Config.Data.Value" />.
		/// </summary>
		/// <param name="obj">the object to convert</param>
		/// <param name="parent">the owning object of <paramref name="obj" /></param>
		/// <returns>a representation of <paramref name="obj" /> as a <see cref="T:IPA.Config.Data.Value" /> structure</returns>
		// Token: 0x06000316 RID: 790
		Value ToValue(object obj, object parent);

		/// <summary>
		/// Converts the given <see cref="T:IPA.Config.Data.Value" /> to the object type handled by this converter.
		/// </summary>
		/// <param name="value">the <see cref="T:IPA.Config.Data.Value" /> to deserialize</param>
		/// <param name="parent">the object that will own the result</param>
		/// <returns>the deserialized object</returns>
		// Token: 0x06000317 RID: 791
		object FromValue(Value value, object parent);

		/// <summary>
		/// Gets the type that this <see cref="T:IPA.Config.Stores.IValueConverter" /> handles.
		/// </summary>
		// Token: 0x17000095 RID: 149
		// (get) Token: 0x06000318 RID: 792
		Type Type { get; }
	}
}
