using System;
using System.IO;
using System.Security.Cryptography;

namespace Mono.CompilerServices.SymbolWriter
{
	// Token: 0x02000214 RID: 532
	internal class SourceFileEntry
	{
		// Token: 0x17000364 RID: 868
		// (get) Token: 0x06000FC5 RID: 4037 RVA: 0x00035517 File Offset: 0x00033717
		public static int Size
		{
			get
			{
				return 8;
			}
		}

		// Token: 0x06000FC6 RID: 4038 RVA: 0x000358C1 File Offset: 0x00033AC1
		public SourceFileEntry(MonoSymbolFile file, string file_name)
		{
			this.file = file;
			this.file_name = file_name;
			this.Index = file.AddSource(this);
			this.creating = true;
		}

		// Token: 0x06000FC7 RID: 4039 RVA: 0x000358EB File Offset: 0x00033AEB
		public SourceFileEntry(MonoSymbolFile file, string sourceFile, byte[] guid, byte[] checksum)
			: this(file, sourceFile, sourceFile, guid, checksum)
		{
		}

		// Token: 0x06000FC8 RID: 4040 RVA: 0x000358F9 File Offset: 0x00033AF9
		public SourceFileEntry(MonoSymbolFile file, string fileName, string sourceFile, byte[] guid, byte[] checksum)
			: this(file, fileName)
		{
			this.guid = guid;
			this.hash = checksum;
			this.sourceFile = sourceFile;
		}

		// Token: 0x17000365 RID: 869
		// (get) Token: 0x06000FC9 RID: 4041 RVA: 0x0003591A File Offset: 0x00033B1A
		public byte[] Checksum
		{
			get
			{
				return this.hash;
			}
		}

		// Token: 0x06000FCA RID: 4042 RVA: 0x00035924 File Offset: 0x00033B24
		internal void WriteData(MyBinaryWriter bw)
		{
			this.DataOffset = (int)bw.BaseStream.Position;
			bw.Write(this.file_name);
			if (this.guid == null)
			{
				this.guid = new byte[16];
			}
			if (this.hash == null)
			{
				try
				{
					using (FileStream fileStream = new FileStream(this.sourceFile, FileMode.Open, FileAccess.Read))
					{
						MD5 md = MD5.Create();
						this.hash = md.ComputeHash(fileStream);
					}
				}
				catch
				{
					this.hash = new byte[16];
				}
			}
			bw.Write(this.guid);
			bw.Write(this.hash);
			bw.Write(this.auto_generated ? 1 : 0);
		}

		// Token: 0x06000FCB RID: 4043 RVA: 0x000359F4 File Offset: 0x00033BF4
		internal void Write(BinaryWriter bw)
		{
			bw.Write(this.Index);
			bw.Write(this.DataOffset);
		}

		// Token: 0x06000FCC RID: 4044 RVA: 0x00035A10 File Offset: 0x00033C10
		internal SourceFileEntry(MonoSymbolFile file, MyBinaryReader reader)
		{
			this.file = file;
			this.Index = reader.ReadInt32();
			this.DataOffset = reader.ReadInt32();
			int num = (int)reader.BaseStream.Position;
			reader.BaseStream.Position = (long)this.DataOffset;
			this.sourceFile = (this.file_name = reader.ReadString());
			this.guid = reader.ReadBytes(16);
			this.hash = reader.ReadBytes(16);
			this.auto_generated = reader.ReadByte() == 1;
			reader.BaseStream.Position = (long)num;
		}

		// Token: 0x17000366 RID: 870
		// (get) Token: 0x06000FCD RID: 4045 RVA: 0x00035AAE File Offset: 0x00033CAE
		// (set) Token: 0x06000FCE RID: 4046 RVA: 0x00035AB6 File Offset: 0x00033CB6
		public string FileName
		{
			get
			{
				return this.file_name;
			}
			set
			{
				this.file_name = value;
			}
		}

		// Token: 0x17000367 RID: 871
		// (get) Token: 0x06000FCF RID: 4047 RVA: 0x00035ABF File Offset: 0x00033CBF
		public bool AutoGenerated
		{
			get
			{
				return this.auto_generated;
			}
		}

		// Token: 0x06000FD0 RID: 4048 RVA: 0x00035AC7 File Offset: 0x00033CC7
		public void SetAutoGenerated()
		{
			if (!this.creating)
			{
				throw new InvalidOperationException();
			}
			this.auto_generated = true;
			this.file.OffsetTable.FileFlags |= OffsetTable.Flags.IsAspxSource;
		}

		// Token: 0x06000FD1 RID: 4049 RVA: 0x00035AF8 File Offset: 0x00033CF8
		public bool CheckChecksum()
		{
			bool flag;
			try
			{
				using (FileStream fileStream = new FileStream(this.sourceFile, FileMode.Open))
				{
					byte[] array = MD5.Create().ComputeHash(fileStream);
					for (int i = 0; i < 16; i++)
					{
						if (array[i] != this.hash[i])
						{
							return false;
						}
					}
					flag = true;
				}
			}
			catch
			{
				flag = false;
			}
			return flag;
		}

		// Token: 0x06000FD2 RID: 4050 RVA: 0x00035B6C File Offset: 0x00033D6C
		public override string ToString()
		{
			return string.Format("SourceFileEntry ({0}:{1})", this.Index, this.DataOffset);
		}

		// Token: 0x040009B2 RID: 2482
		public readonly int Index;

		// Token: 0x040009B3 RID: 2483
		private int DataOffset;

		// Token: 0x040009B4 RID: 2484
		private MonoSymbolFile file;

		// Token: 0x040009B5 RID: 2485
		private string file_name;

		// Token: 0x040009B6 RID: 2486
		private byte[] guid;

		// Token: 0x040009B7 RID: 2487
		private byte[] hash;

		// Token: 0x040009B8 RID: 2488
		private bool creating;

		// Token: 0x040009B9 RID: 2489
		private bool auto_generated;

		// Token: 0x040009BA RID: 2490
		private readonly string sourceFile;
	}
}
