using System;
using System.IO;
using System.Security.Cryptography;

namespace Mono.CompilerServices.SymbolWriter
{
	// Token: 0x02000012 RID: 18
	public class SourceFileEntry
	{
		// Token: 0x17000018 RID: 24
		// (get) Token: 0x06000068 RID: 104 RVA: 0x000037DF File Offset: 0x000019DF
		public static int Size
		{
			get
			{
				return 8;
			}
		}

		// Token: 0x06000069 RID: 105 RVA: 0x00003B8D File Offset: 0x00001D8D
		public SourceFileEntry(MonoSymbolFile file, string file_name)
		{
			this.file = file;
			this.file_name = file_name;
			this.Index = file.AddSource(this);
			this.creating = true;
		}

		// Token: 0x0600006A RID: 106 RVA: 0x00003BB7 File Offset: 0x00001DB7
		public SourceFileEntry(MonoSymbolFile file, string sourceFile, byte[] guid, byte[] checksum)
			: this(file, sourceFile, sourceFile, guid, checksum)
		{
		}

		// Token: 0x0600006B RID: 107 RVA: 0x00003BC5 File Offset: 0x00001DC5
		public SourceFileEntry(MonoSymbolFile file, string fileName, string sourceFile, byte[] guid, byte[] checksum)
			: this(file, fileName)
		{
			this.guid = guid;
			this.hash = checksum;
			this.sourceFile = sourceFile;
		}

		// Token: 0x17000019 RID: 25
		// (get) Token: 0x0600006C RID: 108 RVA: 0x00003BE6 File Offset: 0x00001DE6
		public byte[] Checksum
		{
			get
			{
				return this.hash;
			}
		}

		// Token: 0x0600006D RID: 109 RVA: 0x00003BF0 File Offset: 0x00001DF0
		internal void WriteData(MyBinaryWriter bw)
		{
			this.DataOffset = (int)bw.BaseStream.Position;
			bw.Write(this.file_name);
			if (this.guid == null)
			{
				this.guid = new byte[16];
			}
			if (this.hash == null)
			{
				try
				{
					using (FileStream fileStream = new FileStream(this.sourceFile, FileMode.Open, FileAccess.Read))
					{
						MD5 md = MD5.Create();
						this.hash = md.ComputeHash(fileStream);
					}
				}
				catch
				{
					this.hash = new byte[16];
				}
			}
			bw.Write(this.guid);
			bw.Write(this.hash);
			bw.Write(this.auto_generated ? 1 : 0);
		}

		// Token: 0x0600006E RID: 110 RVA: 0x00003CC0 File Offset: 0x00001EC0
		internal void Write(BinaryWriter bw)
		{
			bw.Write(this.Index);
			bw.Write(this.DataOffset);
		}

		// Token: 0x0600006F RID: 111 RVA: 0x00003CDC File Offset: 0x00001EDC
		internal SourceFileEntry(MonoSymbolFile file, MyBinaryReader reader)
		{
			this.file = file;
			this.Index = reader.ReadInt32();
			this.DataOffset = reader.ReadInt32();
			int num = (int)reader.BaseStream.Position;
			reader.BaseStream.Position = (long)this.DataOffset;
			this.sourceFile = (this.file_name = reader.ReadString());
			this.guid = reader.ReadBytes(16);
			this.hash = reader.ReadBytes(16);
			this.auto_generated = reader.ReadByte() == 1;
			reader.BaseStream.Position = (long)num;
		}

		// Token: 0x1700001A RID: 26
		// (get) Token: 0x06000070 RID: 112 RVA: 0x00003D7A File Offset: 0x00001F7A
		// (set) Token: 0x06000071 RID: 113 RVA: 0x00003D82 File Offset: 0x00001F82
		public string FileName
		{
			get
			{
				return this.file_name;
			}
			set
			{
				this.file_name = value;
			}
		}

		// Token: 0x1700001B RID: 27
		// (get) Token: 0x06000072 RID: 114 RVA: 0x00003D8B File Offset: 0x00001F8B
		public bool AutoGenerated
		{
			get
			{
				return this.auto_generated;
			}
		}

		// Token: 0x06000073 RID: 115 RVA: 0x00003D93 File Offset: 0x00001F93
		public void SetAutoGenerated()
		{
			if (!this.creating)
			{
				throw new InvalidOperationException();
			}
			this.auto_generated = true;
			this.file.OffsetTable.FileFlags |= OffsetTable.Flags.IsAspxSource;
		}

		// Token: 0x06000074 RID: 116 RVA: 0x00003DC4 File Offset: 0x00001FC4
		public bool CheckChecksum()
		{
			bool flag;
			try
			{
				using (FileStream fileStream = new FileStream(this.sourceFile, FileMode.Open))
				{
					byte[] array = MD5.Create().ComputeHash(fileStream);
					for (int i = 0; i < 16; i++)
					{
						if (array[i] != this.hash[i])
						{
							return false;
						}
					}
					flag = true;
				}
			}
			catch
			{
				flag = false;
			}
			return flag;
		}

		// Token: 0x06000075 RID: 117 RVA: 0x00003E38 File Offset: 0x00002038
		public override string ToString()
		{
			return string.Format("SourceFileEntry ({0}:{1})", this.Index, this.DataOffset);
		}

		// Token: 0x04000050 RID: 80
		public readonly int Index;

		// Token: 0x04000051 RID: 81
		private int DataOffset;

		// Token: 0x04000052 RID: 82
		private MonoSymbolFile file;

		// Token: 0x04000053 RID: 83
		private string file_name;

		// Token: 0x04000054 RID: 84
		private byte[] guid;

		// Token: 0x04000055 RID: 85
		private byte[] hash;

		// Token: 0x04000056 RID: 86
		private bool creating;

		// Token: 0x04000057 RID: 87
		private bool auto_generated;

		// Token: 0x04000058 RID: 88
		private readonly string sourceFile;
	}
}
